spring.application.name=booking-system


spring.datasource.url=jdbc:mysql://localhost:3306/appointment_db
spring.datasource.username=root
spring.datasource.password=Anil@2217
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true